// @ts-check
// Generated by michi-docs-site skill.
// Placeholder tokens: {{TITLE}}, {{LOGO_LINE}}, {{SIDEBAR_GROUPS}}
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightThemeRapide from 'starlight-theme-rapide';

export default defineConfig({
	integrations: [
		starlight({
			plugins: [starlightThemeRapide()],
			title: '{{TITLE}}',
			{{LOGO_LINE}}
			customCss: ['./src/styles/michroma-headings.css'],
			sidebar: [
				{{SIDEBAR_GROUPS}}
			],
		}),
	],
});
